#define MOUSEKEY_DELAY 2
#define MOUSEKEY_INTERVAL 6
#define MOUSEKEY_MOVE_DELTA 3
#define MOUSEKEY_TIME_TO_MAX 60
#define MOUSEKEY_WHEEL_DELAY 2
#define MOUSEKEY_WHEEL_INTERVAL 40
#define LED_HITS_TO_REMEMBER 24
#define MASTER_RIGHT
#define SWAP_HANDS_ENABLE
