#ifdef DEBOUNCE
#undef DEBOUNCE
#endif
#define DEBOUNCE 40

#define IGNORE_MOD_TAP_INTERRUPT
#define USB_MAX_POWER_CONSUMPTION 50
#define ONESHOT_TIMEOUT 2000

#define RGB_MATRIX_KEYPRESS
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE
