#define RGBLIGHT_ANIMATIONS
#define USB_POLLING_INTERVAL_MS 1
#define QMK_KEYS_PER_SCAN 8
#undef DEBOUNCE
#define DEBOUNCE 40
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF
/*#define DEBUG_MATRIX_SCAN_RATE*/

#define IGNORE_MOD_TAP_INTERRUPT
#define USB_MAX_POWER_CONSUMPTION 100
