#define RGBLIGHT_ANIMATIONS
#define USB_POLLING_INTERVAL_MS 1
#define TAPPING_FORCE_HOLD
#define PERMISSIVE_HOLD
#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#undef DEBOUNCE
#define DEBOUNCE 0
