#define RGBLIGHT_ANIMATIONS
#define USB_POLLING_INTERVAL_MS 1
#define QMK_KEYS_PER_SCAN 8
#undef DEBOUNCE
#define DEBOUNCE 40
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYERS_OVERRIDE_RGB_OFF
/*#define DEBUG_MATRIX_SCAN_RATE*/

#define IGNORE_MOD_TAP_INTERRUPT
#define USB_MAX_POWER_CONSUMPTION 50
#define ONESHOT_TIMEOUT 2000

#ifdef AUDIO_VOICES
#undef AUDIO_VOICES
#endif

#define MK_3_SPEED
#define MK_MOMENTARY_ACCEL

#define MK_C_OFFSET_0 4
#define MK_C_OFFSET_1 8
#define MK_C_OFFSET_2 64
